# Generated by Django 2.0.6 on 2018-06-06 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videokarta', '0002_auto_20180607_0131'),
        ('proccesor', '0006_auto_20180606_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('dly_chego', models.TextField(null=True, verbose_name='По направлению')),
                ('BIOS', models.TextField(null=True)),
                ('factor_OP', models.TextField(null=True, verbose_name='Форм-фактор ОЗУ')),
                ('sound', models.TextField(null=True, verbose_name='Звук (каналов)')),
                ('pins', models.TextField(null=True, verbose_name='Разъем питания')),
                ('form_factor', models.TextField(null=True, verbose_name='Форм-фактор')),
                ('chipset', models.TextField(null=True, verbose_name='Чипсет')),
                ('OZU', models.TextField(null=True, verbose_name='слоты ОЗУ')),
                ('taktovaya', models.TextField(null=True, verbose_name='Тактовая частота ОЗУ')),
                ('otver', models.TextField(null=True, verbose_name='Разъемы')),
                ('pin_proc', models.TextField(null=True, verbose_name='Питание процессора')),
                ('min_price', models.IntegerField(default=0, null=True, verbose_name='минимальная цена')),
                ('interf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother', to='videokarta.Connection')),
                ('sok', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother', to='proccesor.Soket')),
            ],
            options={
                'verbose_name': 'Материнка',
                'verbose_name_plural': 'Материнка',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price1', models.IntegerField(verbose_name='Цена 1го магазина')),
                ('adress1', models.TextField(verbose_name='ссылка на 1ый магазин')),
                ('price2', models.IntegerField(verbose_name='Цена 2го магазина')),
                ('adress2', models.TextField(verbose_name='ссылка на 2ый магазин')),
                ('price3', models.IntegerField(verbose_name='Цена 3го магазина')),
                ('adress3', models.TextField(verbose_name='ссылка на 3ый магазин')),
                ('price4', models.IntegerField(verbose_name='Цена 4го магазина')),
                ('adress4', models.TextField(verbose_name='ссылка на 4ый магазин')),
                ('price5', models.IntegerField(verbose_name='Цена 5го магазина')),
                ('adress5', models.TextField(verbose_name='ссылка на 5ый магазин')),
                ('price6', models.IntegerField(verbose_name='Цена 6го магазина')),
                ('adress6', models.TextField(verbose_name='ссылка на 6ый магазин')),
                ('price7', models.IntegerField(verbose_name='Цена 7го магазина')),
                ('adress7', models.TextField(verbose_name='ссылка на 7ый магазин')),
                ('price8', models.IntegerField(verbose_name='Цена 8го магазина')),
                ('adress8', models.TextField(verbose_name='ссылка на 8ый магазин')),
                ('price9', models.IntegerField(verbose_name='Цена 9го магазина')),
                ('adress9', models.TextField(verbose_name='ссылка на 9ый магазин')),
                ('price10', models.IntegerField(verbose_name='Цена 10го магазина')),
                ('adress10', models.TextField(verbose_name='ссылка на 10ый магазин')),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tovar_id', to='motherboard.Motherboard')),
            ],
            options={
                'verbose_name': 'Цена на материнку',
                'verbose_name_plural': 'цена на материнку',
            },
        ),
    ]
