# Generated by Django 2.0.6 on 2018-06-07 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('V_eto_obem', models.TextField(verbose_name='Объем ОП')),
                ('count_comp', models.TextField(verbose_name='Планок в комплекте')),
                ('DIMM', models.TextField(verbose_name='форм фактор')),
                ('DDR', models.TextField(verbose_name='DDR')),
                ('freq', models.TextField(verbose_name='частота')),
                ('cooler', models.TextField(verbose_name='Тип охлаждения')),
                ('min_price', models.IntegerField(default=0, null=True, verbose_name='минимальная цена')),
            ],
            options={
                'verbose_name': 'Оперативная память',
                'verbose_name_plural': 'Оперативная память',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price1', models.IntegerField(verbose_name='Цена 1го магазина')),
                ('adress1', models.TextField(verbose_name='ссылка на 1ый магазин')),
                ('price2', models.IntegerField(verbose_name='Цена 2го магазина')),
                ('adress2', models.TextField(verbose_name='ссылка на 2ый магазин')),
                ('price3', models.IntegerField(verbose_name='Цена 3го магазина')),
                ('adress3', models.TextField(verbose_name='ссылка на 3ый магазин')),
                ('price4', models.IntegerField(verbose_name='Цена 4го магазина')),
                ('adress4', models.TextField(verbose_name='ссылка на 4ый магазин')),
                ('price5', models.IntegerField(verbose_name='Цена 5го магазина')),
                ('adress5', models.TextField(verbose_name='ссылка на 5ый магазин')),
                ('price6', models.IntegerField(verbose_name='Цена 6го магазина')),
                ('adress6', models.TextField(verbose_name='ссылка на 6ый магазин')),
                ('price7', models.IntegerField(verbose_name='Цена 7го магазина')),
                ('adress7', models.TextField(verbose_name='ссылка на 7ый магазин')),
                ('price8', models.IntegerField(verbose_name='Цена 8го магазина')),
                ('adress8', models.TextField(verbose_name='ссылка на 8ый магазин')),
                ('price9', models.IntegerField(verbose_name='Цена 9го магазина')),
                ('adress9', models.TextField(verbose_name='ссылка на 9ый магазин')),
                ('price10', models.IntegerField(verbose_name='Цена 10го магазина')),
                ('adress10', models.TextField(verbose_name='ссылка на 10ый магазин')),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oper', to='OP.Operative')),
            ],
            options={
                'verbose_name': 'Цена на оперативку',
                'verbose_name_plural': 'цена на оперативку',
            },
        ),
    ]
