# Generated by Django 2.0.6 on 2018-06-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operative',
            name='freq1',
            field=models.TextField(null=True, verbose_name='пропускная'),
        ),
        migrations.AlterField(
            model_name='operative',
            name='DDR',
            field=models.TextField(null=True, verbose_name='DDR'),
        ),
        migrations.AlterField(
            model_name='operative',
            name='DIMM',
            field=models.TextField(null=True, verbose_name='форм фактор'),
        ),
        migrations.AlterField(
            model_name='operative',
            name='V_eto_obem',
            field=models.TextField(null=True, verbose_name='Объем ОП'),
        ),
        migrations.AlterField(
            model_name='operative',
            name='cooler',
            field=models.TextField(null=True, verbose_name='Тип охлаждения'),
        ),
        migrations.AlterField(
            model_name='operative',
            name='count_comp',
            field=models.TextField(null=True, verbose_name='Планок в комплекте'),
        ),
        migrations.AlterField(
            model_name='operative',
            name='freq',
            field=models.TextField(null=True, verbose_name='частота'),
        ),
        migrations.AlterField(
            model_name='operative',
            name='name',
            field=models.TextField(null=True, verbose_name='Название'),
        ),
    ]
