# Generated by Django 2.0.6 on 2018-06-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_auto_20180609_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyed',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
