# Generated by Django 2.0.6 on 2018-06-06 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price1', models.IntegerField(verbose_name='Цена 1го магазина')),
                ('adress1', models.IntegerField(verbose_name='ссылка на 1ый магазин')),
                ('price2', models.IntegerField(verbose_name='Цена 2го магазина')),
                ('adress2', models.IntegerField(verbose_name='ссылка на 2ый магазин')),
                ('price3', models.IntegerField(verbose_name='Цена 3го магазина')),
                ('adress3', models.IntegerField(verbose_name='ссылка на 3ый магазин')),
                ('price4', models.IntegerField(verbose_name='Цена 4го магазина')),
                ('adress4', models.IntegerField(verbose_name='ссылка на 4ый магазин')),
                ('price5', models.IntegerField(verbose_name='Цена 5го магазина')),
                ('adress5', models.IntegerField(verbose_name='ссылка на 5ый магазин')),
                ('price6', models.IntegerField(verbose_name='Цена 6го магазина')),
                ('adress6', models.IntegerField(verbose_name='ссылка на 6ый магазин')),
                ('price7', models.IntegerField(verbose_name='Цена 7го магазина')),
                ('adress7', models.IntegerField(verbose_name='ссылка на 7ый магазин')),
                ('price8', models.IntegerField(verbose_name='Цена 8го магазина')),
                ('adress8', models.IntegerField(verbose_name='ссылка на 8ый магазин')),
                ('price9', models.IntegerField(verbose_name='Цена 9го магазина')),
                ('adress9', models.IntegerField(verbose_name='ссылка на 9ый магазин')),
                ('price10', models.IntegerField(verbose_name='Цена 10го магазина')),
                ('adress10', models.IntegerField(verbose_name='ссылка на 10ый магазин')),
            ],
        ),
        migrations.CreateModel(
            name='Proc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('code', models.CharField(max_length=200, verbose_name='Код модели')),
                ('cooler', models.BooleanField(default=False, verbose_name='Есть ли куллер')),
                ('series', models.CharField(max_length=200, verbose_name='Серия')),
                ('count_core', models.IntegerField(default=2, verbose_name='Кол-во ядер')),
                ('clock_freq', models.CharField(max_length=50, verbose_name='Тактовая частота')),
                ('freq', models.CharField(max_length=50, verbose_name='Частота')),
                ('proc_tech', models.CharField(max_length=100, verbose_name='Техпроцесс')),
                ('architecture', models.CharField(max_length=100, verbose_name='Архитектура')),
                ('integer_video', models.BooleanField(default=False, verbose_name='Интегрированная графика')),
                ('model_GPU', models.TextField(verbose_name='модель интегр. графики')),
                ('L1', models.CharField(max_length=50, verbose_name='кэш 1го')),
                ('L2', models.CharField(max_length=50, verbose_name='кэш 2го')),
                ('L3', models.CharField(max_length=50, verbose_name='кэш 3го')),
                ('TDP', models.CharField(max_length=50, verbose_name='Тепловыделение')),
                ('sup_instr', models.TextField(verbose_name='Поддержка инструкции')),
                ('max_vol', models.CharField(max_length=50, verbose_name='макс. объем')),
                ('max_kanal', models.CharField(max_length=50, verbose_name='макс. частота')),
                ('soket', models.IntegerField(default=0, verbose_name='Сокет')),
                ('min_price', models.IntegerField(default=0, verbose_name='минимальная цена')),
            ],
            options={
                'verbose_name': 'Процессоры',
                'verbose_name_plural': 'Процессоры',
            },
        ),
        migrations.AddField(
            model_name='price',
            name='tovar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tovar', to='proccesor.Proc'),
        ),
    ]
