# Generated by Django 2.0.6 on 2018-06-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proccesor', '0002_auto_20180606_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='adress1',
            field=models.TextField(verbose_name='ссылка на 1ый магазин'),
        ),
        migrations.AlterField(
            model_name='price',
            name='adress10',
            field=models.TextField(verbose_name='ссылка на 10ый магазин'),
        ),
        migrations.AlterField(
            model_name='price',
            name='adress2',
            field=models.TextField(verbose_name='ссылка на 2ый магазин'),
        ),
        migrations.AlterField(
            model_name='price',
            name='adress3',
            field=models.TextField(verbose_name='ссылка на 3ый магазин'),
        ),
        migrations.AlterField(
            model_name='price',
            name='adress4',
            field=models.TextField(verbose_name='ссылка на 4ый магазин'),
        ),
        migrations.AlterField(
            model_name='price',
            name='adress5',
            field=models.TextField(verbose_name='ссылка на 5ый магазин'),
        ),
        migrations.AlterField(
            model_name='price',
            name='adress6',
            field=models.TextField(verbose_name='ссылка на 6ый магазин'),
        ),
        migrations.AlterField(
            model_name='price',
            name='adress7',
            field=models.TextField(verbose_name='ссылка на 7ый магазин'),
        ),
        migrations.AlterField(
            model_name='price',
            name='adress8',
            field=models.TextField(verbose_name='ссылка на 8ый магазин'),
        ),
        migrations.AlterField(
            model_name='price',
            name='adress9',
            field=models.TextField(verbose_name='ссылка на 9ый магазин'),
        ),
        migrations.AlterField(
            model_name='proc',
            name='clock_freq',
            field=models.IntegerField(verbose_name='Тактовая частота'),
        ),
        migrations.AlterField(
            model_name='proc',
            name='freq',
            field=models.IntegerField(verbose_name='Частота'),
        ),
    ]
