# Generated by Django 2.0.6 on 2018-06-06 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proccesor', '0003_auto_20180606_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название сокета')),
            ],
            options={
                'verbose_name': 'Сокет для процессора',
                'verbose_name_plural': 'Сокет для процессора',
            },
        ),
        migrations.RemoveField(
            model_name='proc',
            name='code',
        ),
        migrations.RemoveField(
            model_name='proc',
            name='soket',
        ),
        migrations.AddField(
            model_name='proc',
            name='sok',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='soket_name', to='proccesor.Soket'),
            preserve_default=False,
        ),
    ]
