# Generated by Django 2.0.6 on 2018-06-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proccesor', '0004_auto_20180606_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proc',
            name='L1',
            field=models.CharField(max_length=50, null=True, verbose_name='кэш 1го'),
        ),
        migrations.AlterField(
            model_name='proc',
            name='L2',
            field=models.CharField(max_length=50, null=True, verbose_name='кэш 2го'),
        ),
        migrations.AlterField(
            model_name='proc',
            name='L3',
            field=models.CharField(max_length=50, null=True, verbose_name='кэш 3го'),
        ),
        migrations.AlterField(
            model_name='proc',
            name='TDP',
            field=models.CharField(max_length=50, null=True, verbose_name='Тепловыделение'),
        ),
        migrations.AlterField(
            model_name='proc',
            name='architecture',
            field=models.CharField(max_length=100, null=True, verbose_name='Архитектура'),
        ),
        migrations.AlterField(
            model_name='proc',
            name='clock_freq',
            field=models.IntegerField(null=True, verbose_name='Тактовая частота'),
        ),
        migrations.AlterField(
            model_name='proc',
            name='count_core',
            field=models.IntegerField(default=2, null=True, verbose_name='Кол-во ядер'),
        ),
        migrations.AlterField(
            model_name='proc',
            name='freq',
            field=models.IntegerField(null=True, verbose_name='Частота'),
        ),
        migrations.AlterField(
            model_name='proc',
            name='max_kanal',
            field=models.CharField(max_length=50, null=True, verbose_name='макс. частота'),
        ),
        migrations.AlterField(
            model_name='proc',
            name='max_vol',
            field=models.CharField(max_length=50, null=True, verbose_name='макс. объем'),
        ),
        migrations.AlterField(
            model_name='proc',
            name='min_price',
            field=models.IntegerField(default=0, null=True, verbose_name='минимальная цена'),
        ),
        migrations.AlterField(
            model_name='proc',
            name='model_GPU',
            field=models.TextField(null=True, verbose_name='модель интегр. графики'),
        ),
        migrations.AlterField(
            model_name='proc',
            name='proc_tech',
            field=models.CharField(max_length=100, null=True, verbose_name='Техпроцесс'),
        ),
        migrations.AlterField(
            model_name='proc',
            name='series',
            field=models.CharField(max_length=200, null=True, verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='proc',
            name='sup_instr',
            field=models.TextField(null=True, verbose_name='Поддержка инструкции'),
        ),
    ]
