# Generated by Django 2.0.6 on 2018-06-06 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proccesor', '0005_auto_20180606_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proc',
            name='clock_freq',
            field=models.TextField(null=True, verbose_name='Тактовая частота'),
        ),
        migrations.AlterField(
            model_name='proc',
            name='count_core',
            field=models.TextField(null=True, verbose_name='Кол-во ядер'),
        ),
        migrations.AlterField(
            model_name='proc',
            name='freq',
            field=models.TextField(null=True, verbose_name='Частота'),
        ),
        migrations.AlterField(
            model_name='proc',
            name='sok',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soket_name', to='proccesor.Soket'),
        ),
    ]
