# Generated by Django 2.0.6 on 2018-06-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proccesor', '0009_auto_20180607_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='proc',
            name='min_price_ad',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='мин адрес'),
        ),
    ]
