# Generated by Django 2.0.6 on 2018-06-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proccesor', '0010_proc_min_price_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proc',
            name='min_price_ad',
            field=models.TextField(blank=True, null=True, verbose_name='мин адрес'),
        ),
    ]
