# Generated by Django 2.0.6 on 2018-06-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proccesor', '0011_auto_20180608_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во магазинов'),
        ),
    ]
