# Generated by Django 2.0.6 on 2018-06-06 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Подключение к матери')),
            ],
            options={
                'verbose_name': 'Интерфейс видеокарты',
                'verbose_name_plural': 'Интерфейс видеокарты',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price1', models.IntegerField(verbose_name='Цена 1го магазина')),
                ('adress1', models.TextField(verbose_name='ссылка на 1ый магазин')),
                ('price2', models.IntegerField(verbose_name='Цена 2го магазина')),
                ('adress2', models.TextField(verbose_name='ссылка на 2ый магазин')),
                ('price3', models.IntegerField(verbose_name='Цена 3го магазина')),
                ('adress3', models.TextField(verbose_name='ссылка на 3ый магазин')),
                ('price4', models.IntegerField(verbose_name='Цена 4го магазина')),
                ('adress4', models.TextField(verbose_name='ссылка на 4ый магазин')),
                ('price5', models.IntegerField(verbose_name='Цена 5го магазина')),
                ('adress5', models.TextField(verbose_name='ссылка на 5ый магазин')),
                ('price6', models.IntegerField(verbose_name='Цена 6го магазина')),
                ('adress6', models.TextField(verbose_name='ссылка на 6ый магазин')),
                ('price7', models.IntegerField(verbose_name='Цена 7го магазина')),
                ('adress7', models.TextField(verbose_name='ссылка на 7ый магазин')),
                ('price8', models.IntegerField(verbose_name='Цена 8го магазина')),
                ('adress8', models.TextField(verbose_name='ссылка на 8ый магазин')),
                ('price9', models.IntegerField(verbose_name='Цена 9го магазина')),
                ('adress9', models.TextField(verbose_name='ссылка на 9ый магазин')),
                ('price10', models.IntegerField(verbose_name='Цена 10го магазина')),
                ('adress10', models.TextField(verbose_name='ссылка на 10ый магазин')),
            ],
            options={
                'verbose_name': 'Цена на видеокарты',
                'verbose_name_plural': 'цена на видеокарты',
            },
        ),
        migrations.CreateModel(
            name='Videocard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('GPU', models.CharField(max_length=200, null=True, verbose_name='Модель GPU')),
                ('memory_vol', models.CharField(max_length=200, null=True, verbose_name='Объем памяти')),
                ('type_memory', models.CharField(max_length=200, null=True, verbose_name='Тип памяти')),
                ('bit_capacity', models.CharField(max_length=200, null=True, verbose_name='Разрядность шины')),
                ('freq_of_work', models.CharField(max_length=200, null=True, verbose_name='Частота работы GPU')),
                ('memory_frequency', models.CharField(max_length=200, null=True, verbose_name='Частота работы памяти')),
                ('process_tech', models.CharField(max_length=200, null=True, verbose_name='Техпроцесс')),
                ('max_resolution', models.CharField(max_length=200, null=True, verbose_name='Макс. разрешение')),
                ('directX', models.CharField(max_length=20, null=True, verbose_name='DirectX')),
                ('openGL', models.CharField(max_length=20, null=True, verbose_name='OpenGL')),
                ('max_monitors', models.CharField(max_length=200, null=True, verbose_name='Макс. мониторов')),
                ('cooling', models.CharField(max_length=200, null=True, verbose_name='Охлаждение')),
                ('power', models.CharField(max_length=200, null=True, verbose_name='Потребляемая мощность')),
                ('length', models.CharField(max_length=200, null=True, verbose_name='Длина видеокарты')),
                ('interf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soket_name', to='videokarta.Connection')),
            ],
            options={
                'verbose_name': 'Видеокарты',
                'verbose_name_plural': 'Видеокарты',
            },
        ),
        migrations.AddField(
            model_name='price',
            name='tovar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tovar_id', to='videokarta.Videocard'),
        ),
    ]
