# Generated by Django 2.0.6 on 2018-06-06 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videokarta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocard',
            name='min_price',
            field=models.IntegerField(default=0, null=True, verbose_name='минимальная цена'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='interf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='int_name', to='videokarta.Connection'),
        ),
    ]
