# Generated by Django 2.0.6 on 2018-06-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videokarta', '0005_auto_20180608_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocard',
            name='count',
        ),
        migrations.AddField(
            model_name='price',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во магазинов'),
        ),
    ]
