# Generated by Django 2.0.6 on 2018-06-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True, verbose_name='Название')),
                ('processor_min', models.TextField(null=True, verbose_name='процессор_мин')),
                ('RAM_min', models.TextField(null=True, verbose_name='оператива_мин')),
                ('videocard_min', models.TextField(null=True, verbose_name='видеокарта_мин')),
                ('memory_min', models.TextField(null=True, verbose_name='ЖД_мин')),
                ('processor_max', models.TextField(null=True, verbose_name='процессор_мин')),
                ('RAM_max', models.TextField(null=True, verbose_name='оператива_мин')),
                ('videocard_max', models.TextField(null=True, verbose_name='видеокарта_мин')),
                ('memory_max', models.TextField(null=True, verbose_name='ЖД_мин')),
            ],
        ),
    ]
