# Generated by Django 2.0.6 on 2018-06-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='img',
            field=models.ImageField(default='', upload_to='image/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
