# Generated by Django 2.0.6 on 2018-06-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_games_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='json_max',
            field=models.TextField(null=True, verbose_name='json'),
        ),
        migrations.AddField(
            model_name='games',
            name='json_min',
            field=models.TextField(null=True, verbose_name='json'),
        ),
    ]
